input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

input_arr = input.splitlines()

for line in input_arr:
    word_arr = line.split('')
    print(word_arr)

#it's a n+1 problem which you have to check every next line of n